import { Game } from "@/interfaces/game";

export const ALLGAMES: Game[] = [
    {
        url: "/games/neon-rush",
        src: "/images/neon-rush-2.webp",
        title: "Neon Rush",
        description: "Immerse yourself in a neon-soaked cyberpunk world, battling rogue AI and hackers in this action-packed adventure.",
        categories: ["Arcade", "Fantasy"],
        stars: 4.4,
        reviews: 201000,
        downloads: 1600000,
    },
    {
        url: "/games/mystic-isles",
        src: "/images/mystic-isles-1.webp",
        title: "Mystic Isles",
        description: "Mystic Isles is a captivating and enchanting fantasy RPG that transports players.",
        categories: ["Strategy", "Adventure"],
        stars: 4.5,
        reviews: 184000,
        downloads: 1400000,
    },
    {
        url: "/games/cosmic-plane",
        src: "/images/cosmic-plane-1.webp",
        title: "Cosmic Plane",
        description: "Cosmic Survival is a thrilling and immersive space exploration and survival game.",
        categories: ["Exploration", "Survival"],
        stars: 4.9,
        reviews: 264000,
        downloads: 2000000,
    },
    {
        url: "/games/dragon-roar",
        src: "/images/dragon-roar-1.webp",
        title: "Dragon Roar",
        description: "Dragon's Roar is a grandiose and immersive high-fantasy RPG that transports players.",
        categories: ["RPG", "Fantasy"],
        stars: 4.7,
        reviews: 153000,
        downloads: 1700000,
    },
    {
        url: "/games/lost-in-time",
        src: "/images/lost-in-time-2.webp",
        title: "Lost in Time",
        description: "Lost in Time is an exhilarating time-travel adventure game will take you on an epic journey.",
        categories: ["Adventure", "Puzzle"],
        stars: 4.6,
        reviews: 293000,
        downloads: 2300000,
    },
    {
        url: "/games/stardew-valley",
        src: "/images/stardew-valley-1.webp",
        title: "Stardew Valley",
        description: "Explore vast, mysterious caves. Encounter dangerous monsters & valuable treasures deep underground!",
        categories: ["Adventure", "Survival"],
        stars: 4.8,
        reviews: 687000,
        downloads: 20000000,
    },
    {
        url: "/games/space-infiltrators",
        src: "/images/space-infiltrators-1.webp",
        title: "Space Infiltrators",
        description: "Combines intense action sequences with strategic decision-making, allowing you to choose your own path and playstyle.",
        categories: ["Sci-Fi", "RPG"],
        stars: 4.7,
        reviews: 384000,
        downloads: 1100000
    },
    {
        url: "/games/enchanted-warriors",
        src: "/images/enchanted-warrior-1.webp",
        title: "Enchanted Warrior",
        description: "Stunning visuals and immersive gameplay, Enchanted Warrior invites you to embark on an epic adventure filled with danger and discovery.",
        categories: ["Action", "Adventure"],
        stars: 4.8,
        reviews: 551000,
        downloads: 980000
    },
];