import { ILanguage } from "@/interfaces/language";

export const LANGUAGES: ILanguage[] = [
    { country: "US", short: "en", language: "English", native_name: "English" },
    { country: "Abkhazia", short: "ab", language: "Abkhaz", native_name: "аҧсуа" },
    { country: "", short: "af", language: "Afrikaans", native_name: "Afrikaans" },
    { country: "", short: "ak", language: "Akan", native_name: "Akan" },
    { country: "Albania", short: "sq", language: "Albanian", native_name: "Shqip" },
    { country: "", short: "am", language: "Amharic", native_name: "አማርኛ" },
    { country: "", short: "ar", language: "Arabic", native_name: "العربية" },
    { country: "", short: "an", language: "Aragonese", native_name: "Aragonés" },
    { country: "Armenia", short: "hy", language: "Armenian", native_name: "Հայերեն" },
    { country: "", short: "as", language: "Assamese", native_name: "অসমীয়া" },
    { country: "", short: "av", language: "Avaric", native_name: "авар мацӀ" },
    { country: "", short: "ae", language: "Avestan", native_name: "avesta" },
    { country: "", short: "ay", language: "Aymara", native_name: "aymar aru" },
    { country: "Azerbaijan", short: "az", language: "Azerbaijani", native_name: "azərbaycan dili" },
    { country: "", short: "bm", language: "Bambara", native_name: "bamanankan" },
    { country: "", short: "ba", language: "Bashkir", native_name: "башҡорт теле" },
    { country: "", short: "eu", language: "Basque", native_name: "euskara" },
    { country: "Belarus", short: "be", language: "Belarusian", native_name: "Беларуская" },
    { country: "", short: "bn", language: "Bengali", native_name: "বাংলা" },
    { country: "", short: "bh", language: "Bihari", native_name: "भोजपुरी" },
    { country: "", short: "bi", language: "Bislama", native_name: "Bislama" },
    { country: "Bosnia", short: "bs", language: "Bosnian", native_name: "bosanski jezik" },
    { country: "", short: "br", language: "Breton", native_name: "brezhoneg" },
    { country: "Bulgaria", short: "bg", language: "Bulgarian", native_name: "български език" },
    { country: "", short: "my", language: "Burmese", native_name: "ဗမာစာ" },
    { country: "", short: "ca", language: "Catalan", native_name: "Català" },
    { country: "", short: "ch", language: "Chamorro", native_name: "Chamoru" },
    { country: "", short: "ce", language: "Chechen", native_name: "нохчийн мотт" },
    { country: "", short: "ny", language: "Chichewa", native_name: "chiCheŵa" },
    { country: "China", short: "zh", language: "Chinese", native_name: "中文" },
    { country: "", short: "cv", language: "Chuvash", native_name: "чӑваш чӗлхи" },
    { country: "", short: "kw", language: "Cornish", native_name: "Kernewek" },
    { country: "", short: "co", language: "Corsican", native_name: "corsu" },
    { country: "", short: "cr", language: "Cree", native_name: "ᓀᐦᐃᔭᐍᐏᐣ" },
    { country: "Croatia", short: "hr", language: "Croatian", native_name: "hrvatski" },
    { country: "Czechia", short: "cs", language: "Czech", native_name: "česky" },
    { country: "Denmark", short: "da", language: "Danish", native_name: "dansk" },
    { country: "", short: "dv", language: "Divehi", native_name: "ދިވެހި" },
    { country: "Netherlands", short: "nl", language: "Dutch", native_name: "Nederlands" },
    { country: "", short: "eo", language: "Esperanto", native_name: "Esperanto" },
    { country: "Estonia", short: "et", language: "Estonian", native_name: "eesti" },
    { country: "", short: "ee", language: "Ewe", native_name: "Eʋegbe" },
    { country: "", short: "fo", language: "Faroese", native_name: "føroyskt" },
    { country: "", short: "fj", language: "Fijian", native_name: "vosa Vakaviti" },
    { country: "Finland", short: "fi", language: "Finnish", native_name: "suomi" },
    { country: "France", short: "fr", language: "French", native_name: "français" },
    { country: "", short: "ff", language: "Fula", native_name: "Fulfulde" },
    { country: "", short: "gl", language: "Galician", native_name: "Galego" },
    { country: "Georgia", short: "ka", language: "Georgian", native_name: "ქართული" },
    { country: "Germany", short: "de", language: "German", native_name: "Deutsch" },
    { country: "Greece", short: "el", language: "Greek", native_name: "Ελληνικά" },
    { country: "", short: "gn", language: "Guaraní", native_name: "Avañeẽ" },
    { country: "", short: "gu", language: "Gujarati", native_name: "ગુજરાતી" },
    { country: "", short: "ht", language: "Haitian", native_name: "Kreyòl ayisyen" },
    { country: "", short: "ha", language: "Hausa", native_name: "هَوُسَ" },
    { country: "", short: "he", language: "Hebrew", native_name: "עברית" },
    { country: "", short: "hz", language: "Herero", native_name: "Otjiherero" },
    { country: "", short: "hi", language: "Hindi", native_name: "हिन्दी, हिंदी" },
    { country: "", short: "ho", language: "Hiri Motu", native_name: "Hiri Motu" },
    { country: "Hungary", short: "hu", language: "Hungarian", native_name: "Magyar" },
    { country: "Indonesia", short: "id", language: "Indonesian", native_name: "Bahasa Indonesia" },
    { country: "Ireland", short: "ga", language: "Irish", native_name: "Gaeilge" },
    { country: "", short: "ig", language: "Igbo", native_name: "Asụsụ Igbo" },
    { country: "", short: "ik", language: "Inupiaq", native_name: "Iñupiaq" },
    { country: "", short: "io", language: "Ido", native_name: "Ido" },
    { country: "Iceland", short: "is", language: "Icelandic", native_name: "Íslenska" },
    { country: "Italy", short: "it", language: "Italian", native_name: "Italiano" },
    { country: "", short: "iu", language: "Inuktitut", native_name: "ᐃᓄᒃᑎᑐᑦ" },
    { country: "Japan", short: "ja", language: "Japanese", native_name: "日本語" },
    { country: "Java", short: "jv", language: "Javanese", native_name: "basa Jawa" },
    { country: "", short: "kl", language: "Kalaallisut", native_name: "kalaallisut" },
    { country: "", short: "kn", language: "Kannada", native_name: "ಕನ್ನಡ" },
    { country: "", short: "kr", language: "Kanuri", native_name: "Kanuri" },
    { country: "", short: "ks", language: "Kashmiri", native_name: "कश्मीरी" },
    { country: "", short: "kk", language: "Kazakh", native_name: "Қазақ тілі" },
    { country: "", short: "km", language: "Khmer", native_name: "ភាសាខ្មែរ" },
    { country: "", short: "ki", language: "Kikuyu", native_name: "Gĩkũyũ" },
    { country: "", short: "rw", language: "Kinyarwanda", native_name: "Ikinyarwanda" },
    { country: "", short: "ky", language: "Kirghiz", native_name: "кыргыз тили" },
    { country: "", short: "kv", language: "Komi", native_name: "коми кыв" },
    { country: "", short: "kg", language: "Kongo", native_name: "KiKongo" },
    { country: "Korea", short: "ko", language: "Korean", native_name: "한국어" },
    { country: "", short: "ku", language: "Kurdish", native_name: "كوردی‎" },
    { country: "", short: "kj", language: "Kwanyama", native_name: "Kuanyama" },
    { country: "", short: "la", language: "Latin", native_name: "latine" },
    { country: "Luxembourg", short: "lb", language: "Luxembourgish", native_name: "Lëtzebuergesch" },
    { country: "", short: "lg", language: "Luganda", native_name: "Luganda" },
    { country: "", short: "li", language: "Limburgish", native_name: "Limburgs" },
    { country: "", short: "ln", language: "Lingala", native_name: "Lingála" },
    { country: "", short: "lo", language: "Lao", native_name: "ພາສາລາວ" },
    { country: "Lithuania", short: "lt", language: "Lithuanian", native_name: "lietuvių kalba" },
    { country: "", short: "lu", language: "Luba-Katanga", native_name: "Luba-Katanga" },
    { country: "Latvia", short: "lv", language: "Latvian", native_name: "latviešu valoda" },
    { country: "", short: "gv", language: "Manx", native_name: "Gaelg" },
    { country: "Macedonia", short: "mk", language: "Macedonian", native_name: "македонски јазик" },
    { country: "", short: "mg", language: "Malagasy", native_name: "Malagasy fiteny" },
    { country: "", short: "ms", language: "Malay", native_name: "بهاس ملايو‎" },
    { country: "", short: "ml", language: "Malayalam", native_name: "മലയാളം" },
    { country: "", short: "mt", language: "Maltese", native_name: "Malti" },
    { country: "", short: "mi", language: "Māori", native_name: "te reo Māori" },
    { country: "", short: "mr", language: "Marathi", native_name: "मराठी" },
    { country: "", short: "mh", language: "Marshallese", native_name: "Kajin M̧ajeļ" },
    { country: "Mongolia", short: "mn", language: "Mongolian", native_name: "монгол" },
    { country: "", short: "na", language: "Nauru", native_name: "Ekakairũ Naoero" },
    { country: "", short: "nv", language: "Navajo", native_name: "Diné bizaad" },
    { country: "", short: "nd", language: "North Ndebele", native_name: "isiNdebele" },
    { country: "", short: "ne", language: "Nepali", native_name: "नेपाली" },
    { country: "", short: "ng", language: "Ndonga", native_name: "Owambo" },
    { country: "Norway", short: "no", language: "Norwegian", native_name: "Norsk" },
    { country: "", short: "ii", language: "Nuosu", native_name: "ꆈꌠ꒿ Nuosuhxop" },
    { country: "", short: "nr", language: "South Ndebele", native_name: "isiNdebele" },
    { country: "", short: "oc", language: "Occitan", native_name: "Occitan" },
    { country: "", short: "oj", language: "Ojibwe", native_name: "ᐊᓂᔑᓈᐯᒧᐎᓐ" },
    { country: "", short: "om", language: "Oromo", native_name: "Afaan Oromoo" },
    { country: "", short: "or", language: "Oriya", native_name: "ଓଡ଼ିଆ" },
    { country: "", short: "os", language: "Ossetian", native_name: "ирон æвзаг" },
    { country: "", short: "pa", language: "Punjabi", native_name: "ਪੰਜਾਬੀ" },
    { country: "", short: "pi", language: "Pāli", native_name: "पाऴि" },
    { country: "Persia", short: "fa", language: "Persian", native_name: "فارسی" },
    { country: "Poland", short: "pl", language: "Polish", native_name: "polski" },
    { country: "", short: "ps", language: "Pashto", native_name: "پښتو" },
    { country: "Portugal", short: "pt", language: "Portuguese", native_name: "Português" },
    { country: "", short: "qu", language: "Quechua", native_name: "Runa Simi" },
    { country: "", short: "rm", language: "Romansh", native_name: "rumantsch grischun" },
    { country: "", short: "rn", language: "Kirundi", native_name: "kiRundi" },
    { country: "Romania", short: "ro", language: "Romanian", native_name: "română" },
    { country: "Russia", short: "ru", language: "Russian", native_name: "русский" },
    { country: "", short: "sa", language: "Sanskrit", native_name: "संस्कृतम्" },
    { country: "", short: "sc", language: "Sardinian", native_name: "sardu" },
    { country: "", short: "sd", language: "Sindhi", native_name: "सिन्धी" },
    { country: "", short: "se", language: "Northern Sami", native_name: "Davvisámegiella" },
    { country: "", short: "sm", language: "Samoan", native_name: "gagana faa Samoa" },
    { country: "", short: "sg", language: "Sango", native_name: "yângâ tî sängö" },
    { country: "Serbia", short: "sr", language: "Serbian", native_name: "српски" },
    { country: "", short: "gd", language: "Gaelic", native_name: "Gàidhlig" },
    { country: "", short: "sn", language: "Shona", native_name: "chiShona" },
    { country: "", short: "si", language: "Sinhalese", native_name: "සිංහල" },
    { country: "", short: "sk", language: "Slovak", native_name: "slovenčina" },
    { country: "", short: "sl", language: "Slovene", native_name: "slovenščina" },
    { country: "Somalia", short: "so", language: "Somali", native_name: "Soomaaliga" },
    { country: "", short: "st", language: "Southern Sotho", native_name: "Sesotho" },
    { country: "Spain", short: "es", language: "Spanish", native_name: "español" },
    { country: "", short: "su", language: "Sundanese", native_name: "Basa Sunda" },
    { country: "", short: "sw", language: "Swahili", native_name: "Kiswahili" },
    { country: "", short: "ss", language: "Swati", native_name: "SiSwati" },
    { country: "Sweden", short: "sv", language: "Swedish", native_name: "svenska" },
    { country: "", short: "ta", language: "Tamil", native_name: "தமிழ்" },
    { country: "", short: "te", language: "Telugu", native_name: "తెలుగు" },
    { country: "", short: "tg", language: "Tajik", native_name: "тоҷикӣ" },
    { country: "Thailand", short: "th", language: "Thai", native_name: "ไทย" },
    { country: "", short: "ti", language: "Tigrinya", native_name: "ትግርኛ" },
    { country: "", short: "bo", language: "Tibetan", native_name: "བོད་ཡིག" },
    { country: "", short: "tk", language: "Turkmen", native_name: "Түркмен" },
    { country: "", short: "tl", language: "Tagalog", native_name: "Tagalog" },
    { country: "", short: "tn", language: "Tswana", native_name: "Setswana" },
    { country: "", short: "to", language: "Tonga", native_name: "faka Tonga" },
    { country: "Turkey", short: "tr", language: "Turkish", native_name: "Türkçe" },
    { country: "", short: "ts", language: "Tsonga", native_name: "Xitsonga" },
    { country: "", short: "tt", language: "Tatar", native_name: "татарча" },
    { country: "", short: "tw", language: "Twi", native_name: "Twi" },
    { country: "", short: "ty", language: "Tahitian", native_name: "Reo Tahiti" },
    { country: "", short: "ug", language: "Uyghur", native_name: "Uyƣurqə" },
    { country: "Ukraine", short: "uk", language: "Ukrainian", native_name: "українська" },
    { country: "", short: "ur", language: "Urdu", native_name: "اردو" },
    { country: "", short: "uz", language: "Uzbek", native_name: "Ўзбек" },
    { country: "", short: "ve", language: "Venda", native_name: "Tshivenḓa" },
    { country: "Vietnam", short: "vi", language: "Vietnamese", native_name: "Tiếng Việt" },
    { country: "", short: "vo", language: "Volapük", native_name: "Volapük" },
    { country: "", short: "wa", language: "Walloon", native_name: "Walon" },
    { country: "", short: "cy", language: "Welsh", native_name: "Cymraeg" },
    { country: "", short: "wo", language: "Wolof", native_name: "Wollof" },
    { country: "", short: "fy", language: "Western Frisian", native_name: "Frysk" },
    { country: "", short: "xh", language: "Xhosa", native_name: "isiXhosa" },
    { country: "", short: "yi", language: "Yiddish", native_name: "ייִדיש" },
    { country: "", short: "yo", language: "Yoruba", native_name: "Yorùbá" },
    { country: "", short: "za", language: "Zhuang", native_name: "Saɯ cueŋƅ" }
]